[project]
name = "ted-super"
version = "0.1.0"
description = "Add a short description here"
authors = [
    { name = "Alex The JPEG", email = "alexthejpeg@gmail.com" }
]
dependencies = ["py-cord~=2.4.1"]
readme = "README.md"
requires-python = ">= 3.8"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
[tool.hatch.metadata]
allow-direct-references = true
