[project]
name = "ted-super"
version = "0.2.0"
description = "Add a short description here"
authors = [
    { name = "Alex The JPEG", email = "alexthejpeg@proton.me" }
]
dependencies = ["py-cord~=2.4.1"]
readme = "README.md"
requires-python = ">= 3.8"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = ["ruff~=0.0.269", "black~=23.3.0"]
[tool.hatch.metadata]
allow-direct-references = true
